const schemes = [
    {
        id: 1,
        name: "Prime Minister's Employment Generation Programme (PMEGP)",
        description: "Credit linked subsidy scheme for generating employment through micro enterprises",
        category: "Employment Generation",
        msmeClass: ["Micro"],
        activity: ["Manufacturing", "Services", "Trading"],
        maxLoan: "₹25 Lakhs (Manufacturing), ₹10 Lakhs (Services)",
        maxLoanAmount: 2500000,
        subsidy: "15-35%",
        subsidyPercentage: 35,
        eligibility: "Age 18+, Educational qualification 8th pass",
        eligibleStates: ["Goa", "Others"],
        eligibleDistricts: ["North Goa", "South Goa", "Others"],
        areaType: "Rural",
        employmentGeneration: true,
        minEmployment: 1,
        maxEmployment: 10,
        womenEntrepreneur: true,
        socialCategory: ["General", "SC", "ST", "OBC"],
        speciallyAbledSupport: true,
        exportOriented: false,
        technologyBased: false,
        interestRate: 8.5,
        applyLink: "https://www.kviconline.gov.in/pmegpeportal/jsp/pmegponline.jsp",
        detailedInfo: {
            objective: "To generate employment opportunities in rural as well as urban areas of the country through setting up of new self-employment ventures/projects/micro enterprises.",
            benefits: [
                "Margin money subsidy @ 15% to 35% of the project cost",
                "Collateral free loan up to ₹10 lakhs for service sector and ₹25 lakhs for manufacturing",
                "Interest subsidy on bank loans",
                "Marketing support through Government e-Marketplace (GeM)"
            ],
            eligibilityDetails: [
                "Individual above 18 years of age",
                "Educational qualification: minimum 8th standard pass",
                "For project costing above ₹10 lakhs in manufacturing and ₹5 lakhs in service, the beneficiary should possess at least 8th standard pass certificate",
                "Only new projects are considered under PMEGP"
            ],
            documents: [
                "Project report",
                "Educational certificates",
                "Identity proof (Aadhaar Card)",
                "Address proof",
                "Caste certificate (if applicable)",
                "Bank account details"
            ],
            applicationProcess: [
                "Visit KVIC online portal",
                "Fill online application form",
                "Upload required documents",
                "Submit application to nodal agency",
                "Attend interview if shortlisted",
                "Get loan sanctioned from bank"
            ]
        }
    },
    {
        id: 2,
        name: "Credit Guarantee Fund Trust for Micro and Small Enterprises (CGTMSE)",
        description: "Collateral-free credit facility for MSMEs",
        category: "Credit Support",
        msmeClass: ["Micro", "Small"],
        activity: ["Manufacturing", "Services", "Trading"],
        maxLoan: "₹2 Crores",
        maxLoanAmount: 20000000,
        subsidy: "Guarantee Coverage",
        subsidyPercentage: 0,
        eligibility: "Existing/New MSMEs",
        eligibleStates: ["Goa", "Others"],
        eligibleDistricts: ["North Goa", "South Goa", "Others"],
        areaType: "Urban",
        employmentGeneration: true,
        minEmployment: 5,
        maxEmployment: 50,
        womenEntrepreneur: true,
        socialCategory: ["General", "SC", "ST", "OBC"],
        speciallyAbledSupport: true,
        exportOriented: true,
        technologyBased: false,
        interestRate: 9.0,
        applyLink: "https://www.cgtmse.in/",
        detailedInfo: {
            objective: "To facilitate flow of credit to the micro and small enterprise sector without the need for collateral security and/or third party guarantees.",
            benefits: [
                "Collateral-free loans up to ₹2 crores",
                "Credit guarantee coverage up to 85% of the sanctioned amount",
                "Reduced documentation and faster processing",
                "Lower interest rates due to guarantee coverage"
            ],
            eligibilityDetails: [
                "Micro and Small Enterprises as defined under MSMED Act 2006",
                "New and existing enterprises are eligible",
                "All new micro and small enterprises are eligible",
                "Existing enterprises should have satisfactory credit record"
            ],
            documents: [
                "Udyam Registration Certificate",
                "Project report/Business plan",
                "Financial statements (for existing units)",
                "Identity and address proof",
                "Bank account statements"
            ],
            applicationProcess: [
                "Approach any CGTMSE member lending institution",
                "Submit loan application with required documents",
                "Bank evaluates the proposal",
                "CGTMSE provides guarantee coverage",
                "Loan sanctioned without collateral"
            ]
        }
    },
    {
        id: 3,
        name: "Technology Upgradation Fund Scheme (TUFS)",
        description: "Technology upgradation in textile and jute industries",
        category: "Technology",
        msmeClass: ["Small", "Medium"],
        activity: ["Manufacturing"],
        maxLoan: "₹30 Crores",
        maxLoanAmount: 300000000,
        subsidy: "10-15%",
        subsidyPercentage: 15,
        eligibility: "Textile manufacturers",
        eligibleStates: ["Maharashtra", "Gujarat", "Karnataka", "Tamil Nadu"],
        eligibleDistricts: ["Mumbai", "Pune", "Ahmedabad", "Surat"],
        areaType: "Urban",
        employmentGeneration: true,
        minEmployment: 20,
        maxEmployment: 250,
        womenEntrepreneur: true,
        socialCategory: ["General", "SC", "ST", "OBC"],
        speciallyAbledSupport: false,
        exportOriented: true,
        technologyBased: true,
        interestRate: 7.5,
        applyLink: "https://texmin.nic.in/schemes-programmes/technology-upgradation-fund-scheme-tufs",
        detailedInfo: {
            objective: "To facilitate technology upgradation of the textile industry by providing subsidized credit for modernization of machinery and equipment.",
            benefits: [
                "Capital investment subsidy @ 10% for general category and 15% for specified categories",
                "Interest reimbursement @ 3% per annum for 7 years",
                "Credit linked capital subsidy",
                "Technology upgradation support"
            ],
            eligibilityDetails: [
                "Textile manufacturing units including spinning, weaving, processing, garments, technical textiles",
                "Jute and jute products manufacturing units",
                "Minimum investment of ₹10 lakhs required",
                "Units should be commercially viable"
            ],
            documents: [
                "Project report with technical details",
                "Udyam Registration Certificate",
                "Environmental clearance (if required)",
                "Land documents",
                "Financial statements",
                "Bank loan sanction letter"
            ],
            applicationProcess: [
                "Submit application to Office of Textile Commissioner",
                "Technical evaluation of the project",
                "Approval from competent authority",
                "Release of subsidy in installments",
                "Monitoring and verification"
            ]
        }
    },
    {
        id: 4,
        name: "Stand Up India Scheme",
        description: "Bank loans for SC/ST and women entrepreneurs",
        category: "Social Inclusion",
        msmeClass: ["Small", "Medium"],
        activity: ["Manufacturing", "Services", "Trading"],
        maxLoan: "₹10 Lakhs to ₹1 Crore",
        maxLoanAmount: 10000000,
        subsidy: "Preferential lending",
        subsidyPercentage: 0,
        eligibility: "SC/ST/Women entrepreneurs",
        eligibleStates: ["Goa", "Others"],
        eligibleDistricts: ["North Goa", "South Goa", "Others"],
        areaType: "Semi-Urban",
        employmentGeneration: true,
        minEmployment: 2,
        maxEmployment: 20,
        womenEntrepreneur: true,
        socialCategory: ["SC", "ST"],
        speciallyAbledSupport: true,
        exportOriented: false,
        technologyBased: false,
        interestRate: 10.5,
        applyLink: "https://www.standupmitra.in/",
        detailedInfo: {
            objective: "To facilitate bank loans between ₹10 lakh and ₹1 crore to at least one Scheduled Caste or Scheduled Tribe borrower and at least one woman borrower per bank branch.",
            benefits: [
                "Bank loans between ₹10 lakh to ₹1 crore",
                "Composite loan covering term loan and working capital",
                "Repayment period up to 7 years with moratorium period up to 18 months",
                "Handholding support through Stand Up Connect Centers"
            ],
            eligibilityDetails: [
                "SC/ST and/or Women entrepreneurs, above 18 years of age",
                "Loan is for setting up a greenfield enterprise in manufacturing, services or trading sector",
                "Borrower should not be in default to any bank or financial institution",
                "In case of non-individual enterprises, 51% shareholding should be with SC/ST and/or Women entrepreneur"
            ],
            documents: [
                "Identity proof (Aadhaar Card)",
                "Address proof",
                "Caste certificate (for SC/ST)",
                "Project report",
                "Educational certificates",
                "Experience certificates (if any)"
            ],
            applicationProcess: [
                "Visit Stand Up Mitra portal or nearest bank branch",
                "Fill online application form",
                "Submit required documents",
                "Bank evaluation and processing",
                "Loan sanction and disbursement"
            ]
        }
    },
    {
        id: 5,
        name: "Mudra Yojana",
        description: "Micro finance scheme for small businesses",
        category: "Micro Finance",
        msmeClass: ["Micro"],
        activity: ["Manufacturing", "Services", "Trading"],
        maxLoan: "₹10 Lakhs",
        maxLoanAmount: 1000000,
        subsidy: "Low interest rates",
        subsidyPercentage: 0,
        eligibility: "Non-corporate small business",
        eligibleStates: ["Goa", "Others"],
        eligibleDistricts: ["North Goa", "South Goa", "Others"],
        areaType: "Rural",
        employmentGeneration: true,
        minEmployment: 1,
        maxEmployment: 5,
        womenEntrepreneur: true,
        socialCategory: ["General", "SC", "ST", "OBC"],
        speciallyAbledSupport: true,
        exportOriented: false,
        technologyBased: false,
        interestRate: 12.0,
        applyLink: "https://www.mudra.org.in/",
        detailedInfo: {
            objective: "To provide loans up to ₹10 lakh to the non-corporate, non-farm small/micro enterprises.",
            benefits: [
                "Shishu: Loans up to ₹50,000",
                "Kishore: Loans from ₹50,001 to ₹5 lakh",
                "Tarun: Loans from ₹5,00,001 to ₹10 lakh",
                "No collateral required for loans up to ₹10 lakh"
            ],
            eligibilityDetails: [
                "Any Indian citizen having a business plan for a non-farm sector income generating activity",
                "Borrower should not be defaulter to any bank or financial institution",
                "For manufacturing enterprises: investment in plant & machinery should not exceed ₹1 crore",
                "For service enterprises: investment in equipment should not exceed ₹50 lakh"
            ],
            documents: [
                "Identity proof (Aadhaar Card, Voter ID, etc.)",
                "Address proof",
                "Business address proof",
                "Income proof",
                "Caste certificate (if applicable)",
                "Quotation of assets to be purchased"
            ],
            applicationProcess: [
                "Approach any bank, NBFC, or MFI",
                "Fill loan application form",
                "Submit required documents",
                "Bank verification and processing",
                "Loan approval and disbursement"
            ]
        }
    },
    {
        id: 6,
        name: "Startup India Scheme",
        description: "Support for innovative startups and entrepreneurs",
        category: "Innovation",
        msmeClass: ["Micro", "Small"],
        activity: ["Services", "Manufacturing"],
        maxLoan: "Various funding options",
        maxLoanAmount: 5000000,
        subsidy: "Tax benefits, IPR support",
        subsidyPercentage: 0,
        eligibility: "Innovative startups",
        eligibleStates: ["Goa", "Others"],
        eligibleDistricts: ["North Goa", "South Goa", "Others"],
        areaType: "Urban",
        employmentGeneration: true,
        minEmployment: 1,
        maxEmployment: 15,
        womenEntrepreneur: true,
        socialCategory: ["General", "SC", "ST", "OBC"],
        speciallyAbledSupport: true,
        exportOriented: false,
        technologyBased: true,
        interestRate: 11.0,
        applyLink: "https://www.startupindia.gov.in/",
        detailedInfo: {
            objective: "To build a strong ecosystem for nurturing innovation and startups in the country that will drive sustainable economic growth and generate large scale employment opportunities.",
            benefits: [
                "Tax exemption for 3 consecutive years",
                "Self-certification under 6 labor and environment laws",
                "Fast-track patent examination with 80% rebate in patent fees",
                "Fund of Funds with corpus of ₹10,000 crores",
                "Easy winding up process within 90 days"
            ],
            eligibilityDetails: [
                "Entity should be incorporated as a private limited company or registered as a partnership firm or a limited liability partnership",
                "Should not be formed by splitting up or reconstruction of a business already in existence",
                "Turnover should not exceed ₹100 crores in any of the previous financial years",
                "Should be working towards innovation, development or improvement of products or processes or services"
            ],
            documents: [
                "Certificate of incorporation",
                "Memorandum and Articles of Association",
                "Brief about the nature of business",
                "Letter of recommendation (if any)",
                "Pitch deck explaining the innovative nature of business"
            ],
            applicationProcess: [
                "Register on Startup India portal",
                "Fill the recognition application",
                "Upload required documents",
                "Submit application for review",
                "Get startup recognition certificate"
            ]
        }
    },
    {
        id: 7,
        name: "Digital India Land Records Modernization",
        description: "Digitization support for land record management",
        category: "Digital Transformation",
        msmeClass: ["Small", "Medium"],
        activity: ["Services"],
        maxLoan: "₹50 Lakhs",
        maxLoanAmount: 5000000,
        subsidy: "50% of project cost",
        subsidyPercentage: 50,
        eligibility: "IT service providers",
        eligibleStates: ["Goa", "Others"],
        eligibleDistricts: ["North Goa", "South Goa", "Others"],
        areaType: "Urban",
        employmentGeneration: true,
        minEmployment: 5,
        maxEmployment: 25,
        womenEntrepreneur: true,
        socialCategory: ["General", "SC", "ST", "OBC"],
        speciallyAbledSupport: false,
        exportOriented: false,
        technologyBased: true,
        interestRate: 9.5,
        applyLink: "https://digitalindia.gov.in/"
    },
    {
        id: 8,
        name: "Khadi and Village Industries Commission (KVIC) Schemes",
        description: "Support for traditional and village industries",
        category: "Rural Development",
        msmeClass: ["Micro", "Small"],
        activity: ["Manufacturing"],
        maxLoan: "₹15 Lakhs",
        maxLoanAmount: 1500000,
        subsidy: "25-50%",
        subsidyPercentage: 50,
        eligibility: "Rural entrepreneurs",
        eligibleStates: ["Goa", "Others"],
        eligibleDistricts: ["North Goa", "South Goa", "Others"],
        areaType: "Rural",
        employmentGeneration: true,
        minEmployment: 2,
        maxEmployment: 10,
        womenEntrepreneur: true,
        socialCategory: ["General", "SC", "ST", "OBC"],
        speciallyAbledSupport: true,
        exportOriented: false,
        technologyBased: false,
        interestRate: 8.0,
        applyLink: "https://www.kvic.org.in/"
    },
    {
        id: 9,
        name: "National Small Industries Corporation (NSIC) Schemes",
        description: "Marketing, technology, and financial support",
        category: "Comprehensive Support",
        msmeClass: ["Small", "Medium"],
        activity: ["Manufacturing", "Services"],
        maxLoan: "₹5 Crores",
        maxLoanAmount: 50000000,
        subsidy: "Various benefits",
        subsidyPercentage: 20,
        eligibility: "Registered MSMEs",
        eligibleStates: ["Goa", "Others"],
        eligibleDistricts: ["North Goa", "South Goa", "Others"],
        areaType: "Urban",
        employmentGeneration: true,
        minEmployment: 10,
        maxEmployment: 100,
        womenEntrepreneur: true,
        socialCategory: ["General", "SC", "ST", "OBC"],
        speciallyAbledSupport: true,
        exportOriented: true,
        technologyBased: false,
        interestRate: 10.0,
        applyLink: "https://www.nsic.co.in/"
    },
    {
        id: 10,
        name: "Coir Board Schemes",
        description: "Development of coir industry",
        category: "Industry Specific",
        msmeClass: ["Micro", "Small"],
        activity: ["Manufacturing"],
        maxLoan: "₹20 Lakhs",
        maxLoanAmount: 2000000,
        subsidy: "25-50%",
        subsidyPercentage: 50,
        eligibility: "Coir industry entrepreneurs",
        eligibleStates: ["Goa", "Others"],
        eligibleDistricts: ["North Goa", "South Goa", "Others"],
        areaType: "Rural",
        employmentGeneration: true,
        minEmployment: 3,
        maxEmployment: 15,
        womenEntrepreneur: true,
        socialCategory: ["General", "SC", "ST", "OBC"],
        speciallyAbledSupport: true,
        exportOriented: true,
        technologyBased: false,
        interestRate: 9.0,
        applyLink: "https://coirboard.gov.in/"
    },
    {
        id: 11,
        name: "Handloom Weavers' Comprehensive Welfare Scheme",
        description: "Support for handloom weavers and their families",
        category: "Welfare",
        msmeClass: ["Micro"],
        activity: ["Manufacturing"],
        maxLoan: "₹5 Lakhs",
        maxLoanAmount: 500000,
        subsidy: "90% for BPL families",
        subsidyPercentage: 90,
        eligibility: "Handloom weavers",
        eligibleStates: ["Goa", "Others"],
        eligibleDistricts: ["North Goa", "South Goa", "Others"],
        areaType: "Rural",
        employmentGeneration: true,
        minEmployment: 1,
        maxEmployment: 5,
        womenEntrepreneur: true,
        socialCategory: ["General", "SC", "ST", "OBC"],
        speciallyAbledSupport: true,
        exportOriented: false,
        technologyBased: false,
        interestRate: 6.5,
        applyLink: "https://handlooms.nic.in/"
    },
    {
        id: 12,
        name: "Scheme for Fund for Regeneration of Traditional Industries (SFURTI)",
        description: "Cluster development for traditional industries",
        category: "Cluster Development",
        msmeClass: ["Micro", "Small"],
        activity: ["Manufacturing"],
        maxLoan: "₹8 Crores per cluster",
        maxLoanAmount: 80000000,
        subsidy: "90% for soft interventions",
        subsidyPercentage: 90,
        eligibility: "Traditional industry clusters",
        eligibleStates: ["Goa", "Others"],
        eligibleDistricts: ["North Goa", "South Goa", "Others"],
        areaType: "Rural",
        employmentGeneration: true,
        minEmployment: 50,
        maxEmployment: 500,
        womenEntrepreneur: true,
        socialCategory: ["General", "SC", "ST", "OBC"],
        speciallyAbledSupport: true,
        exportOriented: false,
        technologyBased: false,
        interestRate: 7.0,
        applyLink: "https://sfurti.msme.gov.in/"
    },
    {
        id: 13,
        name: "Credit Linked Capital Subsidy Scheme (CLCSS)",
        description: "Technology upgradation for small scale industries",
        category: "Technology",
        msmeClass: ["Small"],
        activity: ["Manufacturing"],
        maxLoan: "₹1 Crore",
        maxLoanAmount: 10000000,
        subsidy: "15% of investment",
        subsidyPercentage: 15,
        eligibility: "SSI units for technology upgrade",
        eligibleStates: ["Goa", "Others"],
        eligibleDistricts: ["North Goa", "South Goa", "Others"],
        areaType: "Urban",
        employmentGeneration: true,
        minEmployment: 10,
        maxEmployment: 50,
        womenEntrepreneur: true,
        socialCategory: ["General", "SC", "ST", "OBC"],
        speciallyAbledSupport: false,
        exportOriented: false,
        technologyBased: true,
        interestRate: 8.5,
        applyLink: "https://clcss.dcmsme.gov.in/"
    },
    {
        id: 14,
        name: "Market Development Assistance (MDA) Scheme",
        description: "Export promotion for MSMEs",
        category: "Export Promotion",
        msmeClass: ["Small", "Medium"],
        activity: ["Manufacturing", "Services"],
        maxLoan: "Export finance",
        maxLoanAmount: 25000000,
        subsidy: "Reimbursement of expenses",
        subsidyPercentage: 75,
        eligibility: "Export-oriented MSMEs",
        eligibleStates: ["Goa", "Others"],
        eligibleDistricts: ["North Goa", "South Goa", "Others"],
        areaType: "Urban",
        employmentGeneration: true,
        minEmployment: 15,
        maxEmployment: 100,
        womenEntrepreneur: true,
        socialCategory: ["General", "SC", "ST", "OBC"],
        speciallyAbledSupport: false,
        exportOriented: true,
        technologyBased: false,
        interestRate: 11.5,
        applyLink: "https://mda.msme.gov.in/"
    },
    {
        id: 15,
        name: "Scheme of Micro Finance Programme for Women",
        description: "Microfinance support for women entrepreneurs",
        category: "Women Empowerment",
        msmeClass: ["Micro"],
        activity: ["Services", "Trading"],
        maxLoan: "₹1 Lakh",
        maxLoanAmount: 100000,
        subsidy: "Low interest rates",
        subsidyPercentage: 0,
        eligibility: "Women in SHGs",
        eligibleStates: ["Goa", "Others"],
        eligibleDistricts: ["North Goa", "South Goa", "Others"],
        areaType: "Rural",
        employmentGeneration: true,
        minEmployment: 1,
        maxEmployment: 3,
        womenEntrepreneur: true,
        socialCategory: ["General", "SC", "ST", "OBC"],
        speciallyAbledSupport: true,
        exportOriented: false,
        technologyBased: false,
        interestRate: 6.0,
        applyLink: "https://nrlm.gov.in/"
    },
    {
        id: 16,
        name: "Venture Capital Assistance Scheme",
        description: "Equity support for technology-based startups",
        category: "Venture Capital",
        msmeClass: ["Small", "Medium"],
        activity: ["Services", "Manufacturing"],
        maxLoan: "₹50 Lakhs equity",
        maxLoanAmount: 5000000,
        subsidy: "Equity participation",
        subsidyPercentage: 0,
        eligibility: "Technology startups",
        eligibleStates: ["Goa", "Others"],
        eligibleDistricts: ["North Goa", "South Goa", "Others"],
        areaType: "Urban",
        employmentGeneration: true,
        minEmployment: 5,
        maxEmployment: 25,
        womenEntrepreneur: true,
        socialCategory: ["General", "SC", "ST", "OBC"],
        speciallyAbledSupport: false,
        exportOriented: false,
        technologyBased: true,
        interestRate: 13.0,
        applyLink: "https://vcas.msme.gov.in/"
    },
    {
        id: 17,
        name: "Scheme for Promoting Innovation, Rural Industry and Entrepreneurship (ASPIRE)",
        description: "Promotion of rural entrepreneurship",
        category: "Rural Innovation",
        msmeClass: ["Micro", "Small"],
        activity: ["Manufacturing", "Services"],
        maxLoan: "₹50 Lakhs",
        maxLoanAmount: 5000000,
        subsidy: "Various support",
        subsidyPercentage: 30,
        eligibility: "Rural entrepreneurs",
        eligibleStates: ["Goa", "Others"],
        eligibleDistricts: ["North Goa", "South Goa", "Others"],
        areaType: "Rural",
        employmentGeneration: true,
        minEmployment: 3,
        maxEmployment: 20,
        womenEntrepreneur: true,
        socialCategory: ["General", "SC", "ST", "OBC"],
        speciallyAbledSupport: true,
        exportOriented: false,
        technologyBased: true,
        interestRate: 10.5,
        applyLink: "https://aspire.msme.gov.in/"
    },
    {
        id: 18,
        name: "Zero Defect Zero Effect (ZED) Certification Scheme",
        description: "Quality and environmental certification",
        category: "Quality Certification",
        msmeClass: ["Small", "Medium"],
        activity: ["Manufacturing"],
        maxLoan: "Certification support",
        maxLoanAmount: 1000000,
        subsidy: "80% of certification cost",
        subsidyPercentage: 80,
        eligibility: "Manufacturing MSMEs",
        eligibleStates: ["Goa", "Others"],
        eligibleDistricts: ["North Goa", "South Goa", "Others"],
        areaType: "Urban",
        employmentGeneration: true,
        minEmployment: 10,
        maxEmployment: 100,
        womenEntrepreneur: true,
        socialCategory: ["General", "SC", "ST", "OBC"],
        speciallyAbledSupport: false,
        exportOriented: true,
        technologyBased: false,
        interestRate: 12.5,
        applyLink: "https://zed.msme.gov.in/"
    },
    {
        id: 19,
        name: "Lean Manufacturing Competitiveness Scheme",
        description: "Manufacturing efficiency improvement",
        category: "Manufacturing Excellence",
        msmeClass: ["Small", "Medium"],
        activity: ["Manufacturing"],
        maxLoan: "Consultancy support",
        maxLoanAmount: 2000000,
        subsidy: "90% of consultancy cost",
        subsidyPercentage: 90,
        eligibility: "Manufacturing units",
        eligibleStates: ["Goa", "Others"],
        eligibleDistricts: ["North Goa", "South Goa", "Others"],
        areaType: "Urban",
        employmentGeneration: true,
        minEmployment: 15,
        maxEmployment: 150,
        womenEntrepreneur: true,
        socialCategory: ["General", "SC", "ST", "OBC"],
        speciallyAbledSupport: false,
        exportOriented: false,
        technologyBased: true,
        interestRate: 11.0,
        applyLink: "https://lean.msme.gov.in/"
    },
    {
<<<<<<< HEAD
        id: 20,
=======
        id: 21,
>>>>>>> c57c20c73cabc23eb671137c1cebb445c43a720b
        name: "Intellectual Property Rights (IPR) Scheme",
        description: "Support for patent, trademark, and design registration",
        category: "IP Protection",
        msmeClass: ["Small", "Medium"],
        activity: ["Manufacturing", "Services"],
        maxLoan: "IPR support",
        maxLoanAmount: 500000,
        subsidy: "50-75% of IPR costs",
        subsidyPercentage: 75,
        eligibility: "Innovative MSMEs",
        eligibleStates: ["Goa", "Others"],
        eligibleDistricts: ["North Goa", "South Goa", "Others"],
        areaType: "Urban",
        employmentGeneration: true,
        minEmployment: 3,
        maxEmployment: 20,
        womenEntrepreneur: true,
        socialCategory: ["General", "SC", "ST", "OBC"],
        speciallyAbledSupport: false,
        exportOriented: false,
        technologyBased: true,
        interestRate: 14.0,
        applyLink: "https://ipr.msme.gov.in/"
    },
    {
<<<<<<< HEAD
        id: 21,
=======
        id: 23,
>>>>>>> c57c20c73cabc23eb671137c1cebb445c43a720b
        name: "Procurement and Marketing Support Scheme",
        description: "Government procurement opportunities for MSMEs",
        category: "Marketing Support",
        msmeClass: ["Small", "Medium"],
        activity: ["Manufacturing", "Services"],
        maxLoan: "Marketing support",
        maxLoanAmount: 1000000,
        subsidy: "Tender fee reimbursement",
        subsidyPercentage: 100,
        eligibility: "Registered MSMEs",
        eligibleStates: ["Goa", "Others"],
        eligibleDistricts: ["North Goa", "South Goa", "Others"],
        areaType: "Urban",
        employmentGeneration: true,
        minEmployment: 5,
        maxEmployment: 50,
        womenEntrepreneur: true,
        socialCategory: ["General", "SC", "ST", "OBC"],
        speciallyAbledSupport: false,
        exportOriented: false,
        technologyBased: false,
        interestRate: 15.0,
        applyLink: "https://procurement.msme.gov.in/"
    }
];
